cmskit/products/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',

    url(r'^$', 
        'cmskit.products.views.index', 
        name='products_index'),

    url(r'^(?P<path>(.*))/$', 
        'cmskit.products.views.detail', 
        name='products_detail'),
        
)

cmskit/products/models.py
# -*- coding: utf-8 -*-
import re
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify

from mptt.models import MPTTModel, TreeForeignKey
from cms.models.fields import PlaceholderField
from cms.models import CMSPlugin

from cmskit.products.managers import ProductManager


def get_upload_to(instance, filename):
    return '%s/%s/%s' % (
                str(instance._meta.app_label), 
                str(instance._meta.module_name), 
                re.sub('[^\.0-9a-zA-Z()_-]', '_', filename))


class Category(MPTTModel):

    parent          = TreeForeignKey('self', related_name='children', 
                            null=True, blank=True)
                    
    title           = models.CharField(max_length=216)
    slug            = models.SlugField(max_length=216, blank=True, null=False)
    body            = models.TextField(blank=True, null=True)
                    
    picture         = models.ImageField(_('Picture'), 
                            upload_to=get_upload_to, 
                            width_field='picture_width',
                            height_field='picture_height', 
                            blank=True, null=True)
    picture_width   = models.PositiveSmallIntegerField(_("Picture width"), 
                            editable=False, null=True)
    picture_height  = models.PositiveSmallIntegerField(_("Picture height"), 
                            editable=False, null=True)
                        
    top             = PlaceholderField('top', related_name='products_category_top')
    bottom          = PlaceholderField('bottom', related_name='products_category_bottom')
    
    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ("tree_id", "lft")

    def __unicode__(self):
        return u"%s" % self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)
        
    @models.permalink
    def get_absolute_url(self):
        url = "%s" % self.slug
        page = self
        while page.parent:
            url = "%s/%s" % (page.parent.slug,url)
            page = page.parent
        return ('products_detail', None, {'path': url})
    

class Product(models.Model):

    category        = models.ForeignKey(Category)
                    
    title           = models.CharField(_('Title'), max_length=216)
    slug            = models.SlugField(_('Slug'), max_length=216, blank=True, null=False)
    body            = models.TextField(_('Body'), blank=True, null=True)
                    
    picture         = models.ImageField(_('Picture'), 
                            upload_to=get_upload_to, 
                            width_field='picture_width',
                            height_field='picture_height', 
                            blank=True, null=True)
    picture_width   = models.PositiveSmallIntegerField(_("Picture width"), 
                            editable=False, null=True)
    picture_height  = models.PositiveSmallIntegerField(_("Picture height"), 
                            editable=False, null=True)
                    
    publish         = models.BooleanField(_('Publish'), default=True)
                    
    date_created    = models.DateTimeField(_('Creation Date'), auto_now_add=True)
    date_updated    = models.DateTimeField(_('Update Date'), auto_now=True, 
                            editable=False, blank=True, null=True)
                    
    protein         = models.DecimalField(_('Protein') + ' (%)', 
                            max_digits=5, decimal_places=2, 
                            blank=True, null=True)                      
    total_fat       = models.DecimalField(_('Total Fat') + ' (%)', 
                            max_digits=5, decimal_places=2,
                            blank=True, null=True)                      
    saturated_fat   = models.DecimalField(_('Saturated Fat') + ' (%)', 
                            max_digits=5, decimal_places=2,     
                            blank=True, null=True)                      
    energy          = models.DecimalField(_('Energy') + ' kcal/10', 
                            max_digits=5, decimal_places=2, 
                            blank=True, null=True)
                    
    cooking         = models.TextField(_('Cooking Suggestion'), blank=True, null=True)
    storage         = models.TextField(_('Storage Conditions'), blank=True, null=True)
    tricks          = models.TextField(_('Tricks'), blank=True, null=True)
    notes           = models.TextField(_('Notes'), blank=True, null=True)
                    
    top             = PlaceholderField('top', related_name='products_product_top')
    bottom          = PlaceholderField('bottom', related_name='products_product_bottom')
    
    objects         = ProductManager()
    
    class Meta:
        ordering                = ('category', 'id')
        verbose_name            = _('Product')
        verbose_name_plural     = _('Products')
        get_latest_by           = 'date_created'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Product, self).save(*args, **kwargs)
        
    def __unicode__(self):
        return u"%s" % self.title

    @models.permalink
    def get_absolute_url(self, lang=None):
        url = "%s/%s" % (self.category.slug, self.slug)
        page = self.category
        while page.parent:
           url = "%s/%s" % (page.parent.slug, url)
           page = page.parent
        return ('products_detail', None, {'path': url}) if not lang else \
                    (lang+':products_detail', None, {'path': url})


class Info(models.Model):
    product             = models.ForeignKey(Product)
    
    title               = models.CharField(_('Title'), max_length=216)
                    
    weight              = models.PositiveIntegerField(_('Weight'), 
                                blank=True, null=True, help_text=_('grams'))
    package_quantity    = models.PositiveIntegerField(_('Package Quantity'), 
                                blank=True, null=True)
    barcode             = models.IntegerField(_('Barcode'), 
                                blank=True, null=True)
    shelf_life          = models.PositiveIntegerField(_('Shelf Life'), 
                                blank=True, null=True, help_text=_('days'))
    parcel_quantity     = models.PositiveIntegerField(_('Parcel Quantity'), 
                                blank=True, null=True)
    parcel_weight       = models.PositiveIntegerField(_('Parcel Weight'), 
                                blank=True, null=True, help_text=_('Kilograms'))
    parcel_size         = models.CharField(_('Parcel Size'), max_length=216, 
                                blank=True, null=True, help_text=_('mm'))
    
    class Meta:
        verbose_name            = _('Product information')
        verbose_name_plural     = _('Product informations')


class ProductTeaserPlugin(CMSPlugin):

    product     = models.ForeignKey(Product, blank=True, null=True)
    category    = models.ForeignKey(Category, blank=True, null=True)

    def __unicode__(self):
        return u'%s' % (self.product or self.category or _('All products'))

    def copy_relations(self, oldinstance):
        self.product    = oldinstance.product
        self.category   = oldinstance.category
                

cmskit/products/templates/products/_teaser.html
{% load thumbnail %}
<h4><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></h4>
<a href="{{ product.get_absolute_url }}"><img src="{% thumbnail product.picture 300x150 crop %}" width="300" height="150" alt="{{ product.title }}"></a>

cmskit/products/templates/products/category.html
{% extends "base.html" %}
{% load placeholder placeholder_tags %}

{% block title %}{{ block.super }}: {% if category.parent %}{{ category.parent.title }}: {% endif %}{{ category.title }}{% endblock %}
{% block content %}
{% get_placeholder category.top inherit as top %}
{% get_placeholder category.bottom as bottom %}

{% if top %}
    <section id="top">
        {{ top }}
    </section>
{% endif %}

    <div class="well">
        <h1>{{ category.title }}</h1>
        {{ category.body|linebreaks }}
    </div>
    {% if category.children.all %}
    {% for category in category.children.select_related.all %}
        <div id="cat-{{ category.slug }}">
            <h2><a href="{{ category.get_absolute_url }}">{{ category.title }}</a></h2>
            {{ category.body|linebreaks }}
            <ul>
                {% for product in category.product_set.select_related.all %}
                <li>
                    <h3><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></h3>
                    {{ product.body|linebreaks }}
                </li>                    
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
    {% else %}
    <ul>
    {% for product in category.product_set.select_related.all %}
        <h2><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></h2>
        <p>{{ product.body }}</p>
    {% endfor %}
    </ul>
    {% endif %}

{% if bottom %}
    <section id="bottom">
        {{ bottom }}
    </section>
{% endif %}

{% endblock %}

cmskit/products/templates/products/index.html
{% extends "base.html" %}
{% load get_placeholder_tag %}
{% block content %}
{% get_placeholder "top" as top %}
{% get_placeholder "bottom" as bottom %}
{% if top %}
    <section id="top">
        {{ top }}
    </section>
{% endif %}

{% for group in categories %}
    <div id="cat-{{ group.slug }}">
        <h2><a href="{{ group.get_absolute_url }}">{{ group.title }}</a></h2>
        {% if group.body %}
           {{ group.body|linebreaks }} 
        {% endif %}
        {% if group.product_set.select_related.all %}
        <ul>
            {% for product in group.product_set.select_related.all %}
                <li>
                    <h4><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></h4>
                </li>
            {% endfor %}
        </ul>
        {% endif %}
        {% if group.children.select_related.all %}
        <ul>
            {% for category in group.children.select_related.all  %}
            <li>
                <h3><a href="{{ category.get_absolute_url }}">{{ category.title }}</a></h3>
                {% if category.body %}
                {{ category.body|linebreaks }}    
                {% endif %}
                <ul>
                    {% for product in category.product_set.select_related.all %}
                        <li>
                            <h4><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></h4>
                        </li>
                    {% endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
{% endfor %}

{% if bottom %}
    <section id="bottom">
        {{ bottom }}
    </section>
{% endif %}
{% endblock %}

cmskit/products/templates/products/product.html
{% extends "base.html" %}
{% block title %}{{ block.super }}: {% if product.category.parent %}{{ product.category.parent.title }}: {% endif %}{{ product.category.title }}: {{ product.title }}{% endblock %}

{% load cms_tags i18n get_placeholder_tag thumbnail %}

{% block content %}
{% get_placeholder category.top as top %}
{% get_placeholder category.bottom as bottom %}
{% if top %}
    <section id="top">
        {{ top }}
    </section>
{% endif %}

<div class="row">
    <div class="span4">
        <img src="{% thumbnail product.picture 300x200 crop %}" width="300" height="200" alt="{{ product.title }}">
    </div>
    <div class="span4">
        <h1>{{ product.title }}</h1>
        {{ product.body|linebreaks }}    
    </div>
    <div class="span4">
        <div class="tabbable tabs-below">
        <div class="tab-content">
        {% for info in product.info_set.all %}
          <table class="{% if forloop.first %}active {% endif %}table tab-pane" id="info_{{ info.id }}">
              <caption>{{ info.title }}</caption>
             <tr>
                 <th>{% trans "Weight" %}</th>
                 <td>{{ info.weight }}</td>
             </tr>
             <tr>
                 <th>{% trans "Package Quantity" %}</th>
                 <td>{{ info.package_quantity }}</td>
             </tr>
             <tr>
                 <th>{% trans "Barcode" %}</th>
                 <td>{{ info.barcode }}</td>
             </tr>
             <tr>
                 <th>{% trans "Shelf Life" %}</th>
                 <td>{{ info.shelf_life }}</td>
             </tr>
             <tr>
                 <th>{% trans "Parcel Quantity" %}</th>
                 <td>{{ info.parcel_quantity }}</td>
             </tr>
             <tr>
                 <th>{% trans "Parcel Weight" %}</th>
                 <td>{{ info.parcel_weight }}</td>
             </tr>
             <tr>
                 <th>{% trans "Parcel Size" %}</th>
                 <td>{{ info.parcel_size }}</td>
             </tr>
          </table>     
        {% endfor %}
        </div>
        <ul class="nav nav-tabs" id="extra">
        {% for info in product.info_set.all %}
          <li {% if forloop.first %}
            class="active"
          {% endif %}><a href="#info_{{ info.id }}">{{ info.title }}</a></li>
        {% endfor %}
        </ul>
        </div>
    </div>
    <div class="offset4 span8">
        <table class="table">
            <thead>
              <tr>
                  <th>{% trans "Protein" %}</th>
                  <th>{% trans "Total Fat" %}</th>
                  <th>{% trans "Saturated Fat" %}</th>
                  <th>{% trans "Energy" %}</th>            
              </tr>
            </thead>
              <tr>
                  <td>{{ product.protein }}</td>
                  <td>{{ product.total_fat }}</td>
                  <td>{{ product.saturated_fat }}</td>
                  <td>{{ product.energy }}</td>
              </tr>
        </table>

    </div>

</div>
  
<div class="row">
    <div class="span4">
        {% if product.recipe_set.all %}
        {% with product.recipe_set.all|random as recipe %}
        <h3>{% trans "Bu ürünle pişirin" %}</h3>
        <p><a href="{{ recipe.get_absolute_url }}">{{ recipe.title }}</a></p>
        {% endwith %}
        {% endif %}
    </div>
    <div class="span8">
        <ul class="nav nav-tabs" id="extra">
          <li class="active"><a href="#cooking">{% trans "Cooking Suggestions" %}</a></li>
          <li><a href="#storage">{% trans "Storage Conditions" %}</a></li>
          <li><a href="#tricks">{% trans "Tricks" %}</a></li>
          <li><a href="#notes">{% trans "Notes" %}</a></li>
        </ul>

        <div class="tab-content">
          <div class="tab-pane active" id="cooking">{{ product.cooking }}</div>
          <div class="tab-pane" id="storage">{{ product.storage }}</div>
          <div class="tab-pane" id="tricks">{{ product.tricks }}</div>
          <div class="tab-pane" id="notes">{{ product.notes }}</div>
        </div>
    </div>
</div>  
 
<script>
$('#extra a').click(function (e) {
  e.preventDefault();
  $(this).tab('show');
})
</script>

{% if bottom %}
    <section id="bottom">
        {{ bottom }}
    </section>
{% endif %}
  
{% endblock %}