cmskit/articles/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

urlpatterns = patterns('cmskit.articles.views',

    # url(r'^$', 'index', name='articles_index'),

    url(r'^(?P<slug>[-\w]+)/(?P<pk>\d+)/$', 'article', name='articles_article'),

)

cmskit/articles/models.py
# -*- coding: utf-8 -*-
import re
from datetime import datetime
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify

from cms.models import CMSPlugin, Page
from cms.models.fields import PlaceholderField

from cmskit.articles.managers import ArticleManager

def get_upload_to(instance, filename):
    return '%s/%s/%s' % (
                str(instance._meta.app_label), 
                str(instance._meta.module_name), 
                re.sub('[^\.0-9a-zA-Z()_-]', '_', filename))


class Index(models.Model):

    page        = models.ForeignKey(Page)    
    title       = models.CharField(max_length=216, blank=True)

    class Meta:
        verbose_name        = _('Index')
        verbose_name_plural = _('Indexes')
        ordering = ("title",)

    def __unicode__(self):
        return u"%s" % self.title
        
    def save(self, *args, **kwargs):
        if not self.id and not self.title:
            self.title = self.page
        super(Index, self).save(*args, **kwargs)

class Author(models.Model):
    name            = models.CharField(max_length=216)
    slug            = models.SlugField(max_length=216, blank=True, null=False)
    body            = models.TextField(blank=False, null=False)
    picture         = models.ImageField(_('Picture'), 
                            upload_to=get_upload_to, 
                            width_field='picture_width',
                            height_field='picture_height', 
                            blank=True, null=True)

    picture_width   = models.PositiveSmallIntegerField(_("Picture width"), 
                        editable=False, null=True)
    picture_height  = models.PositiveSmallIntegerField(_("Picture height"), 
                        editable=False, null=True)

    aside           = PlaceholderField('aside', related_name='articles_author_aside')    

    top             = PlaceholderField('top', related_name='articles_author_top')
    bottom          = PlaceholderField('bottom', related_name='articles_author_bottom')
                                              
    class Meta:
        verbose_name        = _('Author')
        verbose_name_plural = _('Authors')
        ordering = ("name",)

    def __unicode__(self):
        return u"%s" % self.name

    @models.permalink
    def get_absolute_url(self):
        return ('articles_author', None, {'slug': self.slug })

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Author, self).save(*args, **kwargs)


class Article(models.Model):
    index           = models.ForeignKey(Index, blank=True, null=True)

    title           = models.CharField(_('Title'), max_length=216)
    slug            = models.SlugField(_('Slug'), max_length=216, blank=True, null=False)
    excerpt         = models.TextField(_('Excerpt'), blank=True, null=True)
    body            = models.TextField(_('Body'), blank=True, null=True)
    picture         = models.ImageField(_('Picture'), 
                            upload_to=get_upload_to, 
                            width_field='picture_width',
                            height_field='picture_height', 
                            blank=True, null=True)

    picture_width   = models.PositiveSmallIntegerField(_("Picture width"), 
                            editable=False, null=True)
    picture_height  = models.PositiveSmallIntegerField(_("Picture height"), 
                            editable=False, null=True)

    publish         = models.BooleanField(_('Publish'), default=False)

    date_created    = models.DateTimeField(_('Creation Date'), auto_now_add=True)
    date_updated    = models.DateTimeField(_('Update Date'), auto_now=True, 
                            editable=False, blank=True, null=True)
    date_published  = models.DateTimeField(_('Publish Date'), blank=True, null=True)

    meta            = PlaceholderField('meta', related_name='articles_article_meta')
    media           = PlaceholderField('media', related_name='articles_article_media')    
    aside           = PlaceholderField('aside', related_name='articles_article_aside')    
                      
    top             = PlaceholderField('top', related_name='articles_article_top')
    bottom          = PlaceholderField('bottom', related_name='articles_article_bottom')
    
    objects         = ArticleManager()
    
    class Meta:
        ordering                = ('-date_created', 'title')
        verbose_name            = _('Article')
        verbose_name_plural     = _('Articles')
        get_latest_by           = 'date_created'

    def __unicode__(self):
        return u"%s" % self.title

    @models.permalink
    def get_absolute_url(self):
        return ('articles_article', None, {'slug': self.slug, 'pk': self.pk })

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        if self.publish and not self.date_published:
            self.date_published = datetime.now()
        super(Article, self).save(*args, **kwargs)


class ArticleIndex(CMSPlugin):
    index           = models.ForeignKey(Index)

    def copy_relations(self, oldinstance):
        self.index = oldinstance.index
    
    def __unicode__(self):
        return u'%s' % self.index.title


class ArticleTeaser(CMSPlugin):
    CHOICES = (
        ('random', _('Random')),
        ('latest', _('Latest'))
    )
    article     = models.ForeignKey(Article, blank=True, null=True, 
                        help_text=_('Which article will be displayed.'))
    index       = models.ForeignKey(Index, blank=True, null=True, 
                        help_text=_('Or, from which index will be displayed.'))
    select      = models.CharField(max_length=9, choices=CHOICES, blank=True, null=True, 
                        help_text=_('How the article will be chosen.'))

    def copy_relations(self, oldinstance):
        self.sections = oldinstance.sections.all()
        

cmskit/articles/forms.py
# -*- coding: utf-8 -*-
from django import forms
from cmskit.articles.models import Index, Article

from cms.plugin_pool import plugin_pool
from cms.plugins.text.widgets.wymeditor_widget import WYMEditor
from cms.plugins.text.settings import USE_TINYMCE

def get_editor_widget():
    """
    Returns the Django form Widget to be used for
    the text area
    """
    #plugins = plugin_pool.get_text_enabled_plugins(self.placeholder, self.page)        
    if USE_TINYMCE and "tinymce" in settings.INSTALLED_APPS:
        from cms.plugins.text.widgets.tinymce_widget import TinyMCEEditor
        return TinyMCEEditor()
    else:
        return WYMEditor()

class IndexForm(forms.ModelForm):
    class Meta:
        model = Index
     
    def __init__(self, *args, **kwargs):
        super(IndexForm, self).__init__(*args, **kwargs)
        choices = [self.fields['page'].choices.__iter__().next()]
        for page in self.fields['page'].queryset:
            choices.append(
                (page.id, ''.join(['- '*page.level, page.__unicode__()]))
            )
        self.fields['page'].choices = choices
        
        
class ArticleForm(forms.ModelForm):
    
    body = forms.CharField(widget=get_editor_widget())
    
    class Meta:
        model = Article

cmskit/articles/views.py
# -*- coding: utf-8 -*-
from django.utils.translation import get_language
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from django.http import Http404
from django.core.paginator import Paginator

from cmskit.articles.models import Article

def index(request):
    articles = Article.objects.select_related().published()
    return render_to_response('articles/index.html', 
                {'articles': articles}, 
                context_instance=RequestContext(request))


def article(request, slug, pk):
    article = get_object_or_404(Article.objects.published().select_related(),
                        publish=True, slug=slug, pk=pk)
                        
    return render_to_response('articles/article.html', 
                {'article':article}, 
                context_instance=RequestContext(request))

cmskit/articles/templates/articles/_breadcrumb.html
{% for ance in ancestors %}
    <li><a href="{{ ance.get_absolute_url }}">{{ ance.get_menu_title }}</a> <span class="divider">/</span></li>
{% endfor %}
<li class="active">{{ article.title }}</li>

cmskit/articles/templates/articles/_index.html
{% load i18n cms_tags sekizai_tags pagination_tags %}
{% addtoblock "css" %}
<link rel="canonical" href="{{ request.current_page.get_absolute_url }}" />
{% endaddtoblock %}
<h1 class="page-header">{% trans "Articles" %}</h1>
{% autopaginate articles 10 %}
{% if articles %}
{% for article in articles %}
<article>
    <h2><a href="{{ page.get_absolute_url }}{{ article.slug }}/{{ article.pk }}">{{ article.title }}</a></h2>
    <p>{{ article.excerpt|linebreaks }}</p>
</article>
{% endfor %}    
{% paginate %}
{% else %}
<p class="alert">{% trans "There aren't any articles" %}</p>
{% endif %}

cmskit/articles/templates/articles/_latest.html
{% load i18n %}
{% if articles %}
<h4>{% trans "Latest articles" %}</h4>
<ul>
{% for article in articles %}
<li><a href="{{ page.get_absolute_url }}{{ article.slug }}/{{ article.pk }}">{{ article.title }}</a></li>
{% endfor %}    
</ul>
{% endif %}

cmskit/articles/templates/articles/_teaser.html
{% load thumbnail %}
<h4><a href="{{ page.get_absolute_url }}{{ article.slug }}/{{ article.pk }}">{{ article.title }}</a></h4>
<a href="{{ page.get_absolute_url }}{{ article.slug }}/{{ article.pk }}" class="thumbnail"><img src="{% thumbnail article.picture 300x150 crop %}" width="300" height="150" alt="{{ article.title }}"></a>

cmskit/articles/templates/articles/article.html
{% extends "base.html" %}
{% load i18n cms_tags menu_tags placeholder_tags get_placeholder_tag %}
{% block content %}
{% get_placeholder article.top as top %}
{% get_placeholder article.bottom as bottom %}
{% get_placeholder article.meta as meta %}
{% get_placeholder article.media as media %}

{% if top %}
    <section id="top">
        {{ top }}
    </section>
{% endif %}

<div class="row">
    <article id="main" class="span8">
        <h1 class="page-header">{{ article.title }}</h1>
        {% if meta %}
        <section id="meta">
            {{ meta }}
        </section>
        {% endif %}
        {{ article.body|safe|linebreaks }}
        {% if media %}
        <section id="media">
            {{ media }}
        </section>
        {% endif %}
    </article>
    <aside id="side" class="span4">
        {% placeholder article.aside or %}
        {% with article.index.article_set.all|slice:":10" as articles and article.index.page as page %}
        {% include "articles/_latest.html" %}
        {% endwith %}
        {% endplaceholder %}
    </aside>    
</div>

{% if bottom %}
    <section id="bottom">
        {{ bottom }}
    </section>
{% endif %}

{% endblock %}

cmskit/articles/templates/articles/breadcrumb.html
{% load menu_tags %}
<ul class="breadcrumb">
    {% show_breadcrumb "articles/_breadcrumb.html" %}
</ul>

cmskit/articles/templates/articles/index.html
{% extends "base.html" %}
{% load get_placeholder_tag %}
{% block content %}
{% get_placeholder "top" as top %}
{% get_placeholder "main" as main %}
{% get_placeholder "side" as side %}
{% get_placeholder "bottom" as bottom %}
{% if top %}
    <section id="top">
        {{ top }}
    </section>
{% endif %}

<div class="row">    
    <section id="main" class="span8">
        {{ main }}
        {% include "articles/_index.html" %}
    </section>
    <section id="side" class="span4">
        {{ side }}
    </section>
</div>

{% if bottom %}
    <section id="bottom">
        {{ bottom }}
    </section>
{% endif %}

{% endblock %}